language: python
# current work around for python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - DJANGO_VERSION=2.1.5
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install coverage
script: coverage run manage.py test
after_success: coverage report
branches:
  only:
    - master
services: postgresql